Lveu 18/rides
RabbitUFC/leva-eu-backend pull request #6
Opened 2022-01-22 20:53 UTC by ericiannj

This is the rides' structure.

2022-01-22 20:55 UTC, artorias-g reviewed
Looks good.

2022-01-22 20:58 UTC, artorias-g approved these changes

2022-01-24 02:01 UTC, Joao-VictorF requested changes
Take a look at my comments =)
In general it's very nice.

2022-01-24 02:01 UTC, Joao-VictorF commented on src/controllers/rides.js
> +      .find({}, '-__v -createdAt -updatedAt -deleted')
If you want to filter by the active attribute (or any other attribute), you should put it inside the `{}` param in `Rides.find`. the first param it's the query 

Something like:
`const data = await Rides
      .find({active: true}, '-__v -createdAt -updatedAt -deleted')`

2022-01-24 02:01 UTC, Joao-VictorF commented on src/models/rides.js
> +  endLocation: [{
here should be only **one** start and end locations, right? so you don't need the `[]` wrapping the object. 
If you add the `[]`, you're saying that this would be a array of Id's from Districts.

2022-01-24 02:01 UTC, Joao-VictorF commented on src/models/rides.js
> +  spots: Number,
what is "spots"?

2022-01-24 19:49 UTC, ericiannj commented on src/controllers/rides.js
> +      .find({}, '-__v -createdAt -updatedAt -deleted')
Ok, got it!

2022-01-24 19:51 UTC, ericiannj commented on src/models/rides.js
> +  spots: Number,
Spots are the vacancies/spaces in the car

2022-01-24 19:57 UTC, ericiannj commented on src/models/rides.js
> +  endLocation: [{
I thought that was it. Will the user be free to write whatever he wants in these spaces (default string - "startLocation: String")?

2022-01-27 20:41 UTC, Joao-VictorF requested changes

2022-01-27 20:41 UTC, Joao-VictorF commented on src/models/rides.js
> +const RidesSchema = new mongoose.Schema({
This model is missing some information, we need the information about the driver and the passangers, right?
Remember to add these attributes to the schema. And the driver id can't be updated after creation.

2022-01-27 20:41 UTC, Joao-VictorF commented on src/controllers/rides.js
> +    const data = await Rides.find(query, '-__v -createdAt -updatedAt -deleted').lean();
You need to populate some fields here, 
like: startLocation, endLocation, pickup points and driver, you're returning only the id's of the documents in the response.

We need the actual information from the document, like name, photo, etc.

2022-01-27 20:41 UTC, Joao-VictorF commented on src/controllers/rides.js
> +      .findById(id)
here you have to populate the same fields from the list method, but also the passangers information.

2022-01-27 20:41 UTC, Joao-VictorF commented on src/models/rides.js
> +  date: [{
remove date and hour fields and add only one `date: Date` field.

2022-01-27 20:41 UTC, Joao-VictorF commented on src/schemas/rides.js
> +exports.RidesSchema = Joi.object({
remember to update your models changes here in the schema. Also create a Schema for update method, because the body will be slightly different. like the driver field that can't be updated.

2022-01-29 14:06 UTC, ericiannj commented on src/models/rides.js
> +  date: [{
So will the date field pick information of two inputs, right? [thinking about the user interface]

2022-01-29 22:46 UTC, merged